### ISSUE TITLE
Export SIA 405 Abwasser:  Error

### ISSUE THREAD

**Issue by urskaufmann** [teksi/wastewater#82] opened 2024-01-15 21:55 UTC
Export just 3 reach records out of the demo dataset (with datenherr): OK

Export all records, new digitized records not all with datenherr: Error

Ein Fehler trat bei der Ausführung von Python-Code auf: 

sqlalchemy.exc.IntegrityError: (psycopg2.errors.NotNullViolation) null value in column "datenherrref" of relation "vsa_baseclass" violates not-null constraint DETAIL:  Failing row contains (10, null, null). [SQL: INSERT INTO pg2ili_abwasser.vsa_baseclass (t_id, datenherrref, datenlieferantref) VALUES (%(t_id)s, %(datenherrref)s, %(datenlieferantref)s)] [parameters: ({'t_id': 10, 'datenherrref': None, 'datenlieferantref': None}, {'t_id': 11, 'datenherrref': None, 'datenlieferantref': None}, {'t_id': 12, 'datenherrref': None, 'datenlieferantref': None}, {'t_id': 13, 'datenherrref': None, 'datenlieferantref': None}, {'t_id': 14, 'datenherrref': 5, 'datenlieferantref': 6}, {'t_id': 15, 'datenherrref': 5, 'datenlieferantref': 6}, {'t_id': 16, 'datenherrref': 5, 'datenlieferantref': 6}, {'t_id': 17, 'datenherrref': 5, 'datenlieferantref': 6}  ... displaying 10 of 106 total bound parameter sets ...  {'t_id': 114, 'datenherrref': 5, 'datenlieferantref': 6}, {'t_id': 115, 'datenherrref': 5, 'datenlieferantref': 6})] (Background on this error at: http://sqlalche.me/e/13/gkpj) 
Traceback (most recent call last):
  File "C:\PROGRA~1\QGIS3\apps\Python39\lib\site-packages\sqlalchemy\engine\base.py", line 1256, in _execute_context
    self.dialect.do_executemany(
  File "C:\PROGRA~1\QGIS3\apps\Python39\lib\site-packages\sqlalchemy\dialects\postgresql\psycopg2.py", line 912, in do_executemany
    cursor.executemany(statement, parameters)
psycopg2.errors.NotNullViolation: null value in column "datenherrref" of relation "vsa_baseclass" violates not-null constraint
DETAIL:  Failing row contains (10, null, null).

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users/KAU/AppData/Roaming/QGIS/QGIS3\profiles\tww_test/python/plugins\teksi_wastewater\teksi_wastewater_plugin.py", line 474, in actionExportClicked
    self.interlisImporterExporter.action_export()
  File "C:\Users/KAU/AppData/Roaming/QGIS/QGIS3\profiles\tww_test/python/plugins\teksi_wastewater\interlis\gui\interlis_importer_exporter.py", line 129, in action_export
    raise exception
  File "C:\Users/KAU/AppData/Roaming/QGIS/QGIS3\profiles\tww_test/python/plugins\teksi_wastewater\interlis\gui\interlis_importer_exporter.py", line 113, in action_export
    self._action_export()
  File "C:\Users/KAU/AppData/Roaming/QGIS/QGIS3\profiles\tww_test/python/plugins\teksi_wastewater\interlis\gui\interlis_importer_exporter.py", line 335, in _action_export
    self._export_to_intermediate_schema(
  File "C:\Users/KAU/AppData/Roaming/QGIS/QGIS3\profiles\tww_test/python/plugins\teksi_wastewater\interlis\gui\interlis_importer_exporter.py", line 411, in _export_to_intermediate_schema
    twwInterlisExporter.tww_export()
  File "C:\Users/KAU/AppData/Roaming/QGIS/QGIS3\profiles\tww_test/python/plugins\teksi_wastewater\interlis\interlis_model_mapping\interlis_exporter_to_intermediate_schema.py", line 61, in tww_export
    raise exception
  File "C:\Users/KAU/AppData/Roaming/QGIS/QGIS3\profiles\tww_test/python/plugins\teksi_wastewater\interlis\interlis_model_mapping\interlis_exporter_to_intermediate_schema.py", line 56, in tww_export
    self._tww_export()
  File "C:\Users/KAU/AppData/Roaming/QGIS/QGIS3\profiles\tww_test/python/plugins\teksi_wastewater\interlis\interlis_model_mapping\interlis_exporter_to_intermediate_schema.py", line 75, in _tww_export
    self._export_channel()
  File "C:\Users/KAU/AppData/Roaming/QGIS/QGIS3\profiles\tww_test/python/plugins\teksi_wastewater\interlis\interlis_model_mapping\interlis_exporter_to_intermediate_schema.py", line 199, in _export_channel
    self.abwasser_session.flush()
  File "C:\PROGRA~1\QGIS3\apps\Python39\lib\site-packages\sqlalchemy\orm\session.py", line 2540, in flush
    self._flush(objects)
  File "C:\PROGRA~1\QGIS3\apps\Python39\lib\site-packages\sqlalchemy\orm\session.py", line 2682, in _flush
    transaction.rollback(_capture_exception=True)
  File "C:\PROGRA~1\QGIS3\apps\Python39\lib\site-packages\sqlalchemy\util\langhelpers.py", line 68, in __exit__
    compat.raise_(
  File "C:\PROGRA~1\QGIS3\apps\Python39\lib\site-packages\sqlalchemy\util\compat.py", line 182, in raise_
    raise exception
  File "C:\PROGRA~1\QGIS3\apps\Python39\lib\site-packages\sqlalchemy\orm\session.py", line 2642, in _flush
    flush_context.execute()
  File "C:\PROGRA~1\QGIS3\apps\Python39\lib\site-packages\sqlalchemy\orm\unitofwork.py", line 422, in execute
    rec.execute(self)
  File "C:\PROGRA~1\QGIS3\apps\Python39\lib\site-packages\sqlalchemy\orm\unitofwork.py", line 586, in execute
    persistence.save_obj(
  File "C:\PROGRA~1\QGIS3\apps\Python39\lib\site-packages\sqlalchemy\orm\persistence.py", line 239, in save_obj
    _emit_insert_statements(
  File "C:\PROGRA~1\QGIS3\apps\Python39\lib\site-packages\sqlalchemy\orm\persistence.py", line 1083, in _emit_insert_statements
    c = cached_connections[connection].execute(statement, multiparams)
  File "C:\PROGRA~1\QGIS3\apps\Python39\lib\site-packages\sqlalchemy\engine\base.py", line 1011, in execute
    return meth(self, multiparams, params)
  File "C:\PROGRA~1\QGIS3\apps\Python39\lib\site-packages\sqlalchemy\sql\elements.py", line 298, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "C:\PROGRA~1\QGIS3\apps\Python39\lib\site-packages\sqlalchemy\engine\base.py", line 1124, in _execute_clauseelement
    ret = self._execute_context(
  File "C:\PROGRA~1\QGIS3\apps\Python39\lib\site-packages\sqlalchemy\engine\base.py", line 1316, in _execute_context
    self._handle_dbapi_exception(
  File "C:\PROGRA~1\QGIS3\apps\Python39\lib\site-packages\sqlalchemy\engine\base.py", line 1510, in _handle_dbapi_exception
    util.raise_(
  File "C:\PROGRA~1\QGIS3\apps\Python39\lib\site-packages\sqlalchemy\util\compat.py", line 182, in raise_
    raise exception
  File "C:\PROGRA~1\QGIS3\apps\Python39\lib\site-packages\sqlalchemy\engine\base.py", line 1256, in _execute_context
    self.dialect.do_executemany(
  File "C:\PROGRA~1\QGIS3\apps\Python39\lib\site-packages\sqlalchemy\dialects\postgresql\psycopg2.py", line 912, in do_executemany
    cursor.executemany(statement, parameters)
sqlalchemy.exc.IntegrityError: (psycopg2.errors.NotNullViolation) null value in column "datenherrref" of relation "vsa_baseclass" violates not-null constraint
DETAIL:  Failing row contains (10, null, null).

[SQL: INSERT INTO pg2ili_abwasser.vsa_baseclass (t_id, datenherrref, datenlieferantref) VALUES (%(t_id)s, %(datenherrref)s, %(datenlieferantref)s)]
[parameters: ({'t_id': 10, 'datenherrref': None, 'datenlieferantref': None}, {'t_id': 11, 'datenherrref': None, 'datenlieferantref': None}, {'t_id': 12, 'datenherrref': None, 'datenlieferantref': None}, {'t_id': 13, 'datenherrref': None, 'datenlieferantref': None}, {'t_id': 14, 'datenherrref': 5, 'datenlieferantref': 6}, {'t_id': 15, 'datenherrref': 5, 'datenlieferantref': 6}, {'t_id': 16, 'datenherrref': 5, 'datenlieferantref': 6}, {'t_id': 17, 'datenherrref': 5, 'datenlieferantref': 6}  ... displaying 10 of 106 total bound parameter sets ...  {'t_id': 114, 'datenherrref': 5, 'datenlieferantref': 6}, {'t_id': 115, 'datenherrref': 5, 'datenlieferantref': 6})]
(Background on this error at: http://sqlalche.me/e/13/gkpj)

Python-Version: 3.9.5 (tags/v3.9.5:0a7dcbd, May  3 2021, 17:27:52) [MSC v.1928 64 bit (AMD64)] 
QGIS-Version: 3.28.6-Firenze Firenze, 868c9fa03b 

Python-Pfad:
C:/PROGRA~1/QGIS3/apps/qgis-ltr/./python
C:/Users/KAU/AppData/Roaming/QGIS/QGIS3\profiles\tww_test/python
C:/Users/KAU/AppData/Roaming/QGIS/QGIS3\profiles\tww_test/python/plugins
C:/PROGRA~1/QGIS3/apps/qgis-ltr/./python/plugins
C:\PROGRA~1\QGIS3\apps\grass\grass82\etc\python
C:\Windows\system32
C:\Program Files\QGIS3\bin\python39.zip
C:\PROGRA~1\QGIS3\apps\Python39\DLLs
C:\PROGRA~1\QGIS3\apps\Python39\lib
C:\Program Files\QGIS3\bin
C:\PROGRA~1\QGIS3\apps\Python39
C:\PROGRA~1\QGIS3\apps\Python39\lib\site-packages
C:\PROGRA~1\QGIS3\apps\Python39\lib\site-packages\win32
C:\PROGRA~1\QGIS3\apps\Python39\lib\site-packages\win32\lib
C:\PROGRA~1\QGIS3\apps\Python39\lib\site-packages\Pythonwin
C:/Users/KAU/AppData/Roaming/QGIS/QGIS3\profiles\tww_test/python
T:/12_GIS/01_QGIS/QGEP/qgep-test/tww_project_2020/test
C:\Users/KAU/AppData/Roaming/QGIS/QGIS3\profiles\tww_test/python/plugins\teksi_wastewater\interlis\gui\..\..
.

**Comment by urskaufmann** [comment] 2024-01-16 14:43
... I am not able to find all these empty fields dataowner / dataprovider. They are in tables that are not in the project. The message does not help -> I will make a suggestion for this problem

**Comment by domi4484** [comment] 2024-01-16 15:57
To get a valid XTF dataowner / dataprovider must be set to a valid organisation. I agree that the error message is not very helpful

**Comment by urskaufmann** [comment] 2024-01-16 16:20
I deleted the records of the layers in QGIS (exception: organisation and pipe_profile). 
Then imported the test-dataset-dss again with the import-function.

Then exported again dss, without labels and got this error below.
The problem of this errormessage is: Key = 489 is not an obj_id, it's a transfer-id. The user can not find the record with the error.
And of course: if I have imported successfully and make no changes, it should be possible to export without error. Something is not ok.

Ein Fehler trat bei der Ausführung von Python-Code auf: 

sqlalchemy.exc.IntegrityError: (psycopg2.errors.ForeignKeyViolation) insert or update on table "abwassernetzelement" violates foreign key constraint "abwassernetzelement_abwasserbauwerkref_fkey" DETAIL:  Key (abwasserbauwerkref)=(489) is not present in table "abwasserbauwerk". (Background on this error at: http://sqlalche.me/e/13/gkpj) 
Traceback (most recent call last):
  File "C:\PROGRA~1\QGIS3\apps\Python39\lib\site-packages\sqlalchemy\engine\base.py", line 771, in _commit_impl
    self.engine.dialect.do_commit(self.connection)
  File "C:\PROGRA~1\QGIS3\apps\Python39\lib\site-packages\sqlalchemy\engine\default.py", line 561, in do_commit
    dbapi_connection.commit()
psycopg2.errors.ForeignKeyViolation: insert or update on table "abwassernetzelement" violates foreign key constraint "abwassernetzelement_abwasserbauwerkref_fkey"
DETAIL:  Key (abwasserbauwerkref)=(489) is not present in table "abwasserbauwerk".


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users/KAU/AppData/Roaming/QGIS/QGIS3\profiles\tww_test/python/plugins\teksi_wastewater\teksi_wastewater_plugin.py", line 474, in actionExportClicked
    self.interlisImporterExporter.action_export()
  File "C:\Users/KAU/AppData/Roaming/QGIS/QGIS3\profiles\tww_test/python/plugins\teksi_wastewater\interlis\gui\interlis_importer_exporter.py", line 129, in action_export
    raise exception
  File "C:\Users/KAU/AppData/Roaming/QGIS/QGIS3\profiles\tww_test/python/plugins\teksi_wastewater\interlis\gui\interlis_importer_exporter.py", line 113, in action_export
    self._action_export()
  File "C:\Users/KAU/AppData/Roaming/QGIS/QGIS3\profiles\tww_test/python/plugins\teksi_wastewater\interlis\gui\interlis_importer_exporter.py", line 336, in _action_export
    self._export_to_intermediate_schema(
  File "C:\Users/KAU/AppData/Roaming/QGIS/QGIS3\profiles\tww_test/python/plugins\teksi_wastewater\interlis\gui\interlis_importer_exporter.py", line 412, in _export_to_intermediate_schema
    twwInterlisExporter.tww_export()
  File "C:\Users/KAU/AppData/Roaming/QGIS/QGIS3\profiles\tww_test/python/plugins\teksi_wastewater\interlis\interlis_model_mapping\interlis_exporter_to_intermediate_schema.py", line 61, in tww_export
    raise exception
  File "C:\Users/KAU/AppData/Roaming/QGIS/QGIS3\profiles\tww_test/python/plugins\teksi_wastewater\interlis\interlis_model_mapping\interlis_exporter_to_intermediate_schema.py", line 57, in tww_export
    self.abwasser_session.commit()
  File "C:\PROGRA~1\QGIS3\apps\Python39\lib\site-packages\sqlalchemy\orm\session.py", line 1046, in commit
    self.transaction.commit()
  File "C:\PROGRA~1\QGIS3\apps\Python39\lib\site-packages\sqlalchemy\orm\session.py", line 508, in commit
    t[1].commit()
  File "C:\PROGRA~1\QGIS3\apps\Python39\lib\site-packages\sqlalchemy\engine\base.py", line 1762, in commit
    self._do_commit()
  File "C:\PROGRA~1\QGIS3\apps\Python39\lib\site-packages\sqlalchemy\engine\base.py", line 1793, in _do_commit
    self.connection._commit_impl()
  File "C:\PROGRA~1\QGIS3\apps\Python39\lib\site-packages\sqlalchemy\engine\base.py", line 773, in _commit_impl
    self._handle_dbapi_exception(e, None, None, None, None)
  File "C:\PROGRA~1\QGIS3\apps\Python39\lib\site-packages\sqlalchemy\engine\base.py", line 1510, in _handle_dbapi_exception
    util.raise_(
  File "C:\PROGRA~1\QGIS3\apps\Python39\lib\site-packages\sqlalchemy\util\compat.py", line 182, in raise_
    raise exception
  File "C:\PROGRA~1\QGIS3\apps\Python39\lib\site-packages\sqlalchemy\engine\base.py", line 771, in _commit_impl
    self.engine.dialect.do_commit(self.connection)
  File "C:\PROGRA~1\QGIS3\apps\Python39\lib\site-packages\sqlalchemy\engine\default.py", line 561, in do_commit
    dbapi_connection.commit()
sqlalchemy.exc.IntegrityError: (psycopg2.errors.ForeignKeyViolation) insert or update on table "abwassernetzelement" violates foreign key constraint "abwassernetzelement_abwasserbauwerkref_fkey"
DETAIL:  Key (abwasserbauwerkref)=(489) is not present in table "abwasserbauwerk".

(Background on this error at: http://sqlalche.me/e/13/gkpj)


Python-Version: 3.9.5 (tags/v3.9.5:0a7dcbd, May  3 2021, 17:27:52) [MSC v.1928 64 bit (AMD64)] 
QGIS-Version: 3.28.6-Firenze Firenze, 868c9fa03b 

Python-Pfad:
C:/PROGRA~1/QGIS3/apps/qgis-ltr/./python
C:/Users/KAU/AppData/Roaming/QGIS/QGIS3\profiles\tww_test/python
C:/Users/KAU/AppData/Roaming/QGIS/QGIS3\profiles\tww_test/python/plugins
C:/PROGRA~1/QGIS3/apps/qgis-ltr/./python/plugins
C:\PROGRA~1\QGIS3\apps\grass\grass82\etc\python
C:\Program Files\QGIS3\bin
C:\Program Files\QGIS3\bin\python39.zip
C:\PROGRA~1\QGIS3\apps\Python39\DLLs
C:\PROGRA~1\QGIS3\apps\Python39\lib
C:\PROGRA~1\QGIS3\apps\Python39
C:\PROGRA~1\QGIS3\apps\Python39\lib\site-packages
C:\PROGRA~1\QGIS3\apps\Python39\lib\site-packages\win32
C:\PROGRA~1\QGIS3\apps\Python39\lib\site-packages\win32\lib
C:\PROGRA~1\QGIS3\apps\Python39\lib\site-packages\Pythonwin
C:/Users/KAU/AppData/Roaming/QGIS/QGIS3\profiles\tww_test/python
T:/12_GIS/01_QGIS/QGEP/qgep-test/tww_project_2020/test kau
C:\Users/KAU/AppData/Roaming/QGIS/QGIS3\profiles\tww_test/python/plugins\teksi_wastewater\interlis\gui\..\..
.

**Comment by urskaufmann** [comment] 2024-01-16 21:09
If I select with netfollowing all reaches above manhole 1.001 and export just the selection, the DSS export works.

**Comment by domi4484** [comment] 2024-01-17 09:32
> And of course: if I have imported successfully and make no changes, it should be possible to export without error. Something is not ok.

Yes, but you wrote that you don't deleted pipe_profile. Maybe is there some more invalid data still in the DB?

If you try with a clean database you get the same error?

**Comment by domi4484** [comment] 2024-01-17 10:34
@urskaufmann I can reproduce as well now. Will check it out

**Comment by domi4484** [comment] 2024-01-18 08:41
@urskaufmann I attached a new version of the plugin [here](https://github.com/teksi/wastewater/discussions/72#discussioncomment-8166403), should fix this issues

**Comment by urskaufmann** [comment] 2024-01-18 12:47
I get now this error: 
Could not create the ili2pg schema: Open the logs for more details on the error.

and in the logfile: Error: SIA405_ABWASSER_2020_1_LV95: model not found

tried also with export to DSS -> same error (model not found)

**Comment by urskaufmann** [comment] 2024-01-18 12:50
By the way: when installing this new plugin, I got this error (but installation was then successful)

Konnte Erweiterung 'plugin/teksi_wastewater' nicht laden 

ModuleNotFoundError: No module named 'plugin/teksi_wastewater' 
Traceback (most recent call last):
  File "C:\PROGRA~1/QGIS3/apps/qgis-ltr/./python\qgis\utils.py", line 401, in loadPlugin
    __import__(packageName)
  File "C:\PROGRA~1/QGIS3/apps/qgis-ltr/./python\qgis\utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
ModuleNotFoundError: No module named 'plugin/teksi_wastewater'


Python-Version: 3.9.5 (tags/v3.9.5:0a7dcbd, May  3 2021, 17:27:52) [MSC v.1928 64 bit (AMD64)] 
QGIS-Version: 3.28.6-Firenze Firenze, 868c9fa03b 

Python-Pfad:
C:/PROGRA~1/QGIS3/apps/qgis-ltr/./python
C:/Users/KAU/AppData/Roaming/QGIS/QGIS3\profiles\tww_test/python
C:/Users/KAU/AppData/Roaming/QGIS/QGIS3\profiles\tww_test/python/plugins
C:/PROGRA~1/QGIS3/apps/qgis-ltr/./python/plugins
C:\PROGRA~1\QGIS3\apps\grass\grass82\etc\python
C:\Program Files\QGIS3\bin
C:\Program Files\QGIS3\bin\python39.zip
C:\PROGRA~1\QGIS3\apps\Python39\DLLs
C:\PROGRA~1\QGIS3\apps\Python39\lib
C:\PROGRA~1\QGIS3\apps\Python39
C:\PROGRA~1\QGIS3\apps\Python39\lib\site-packages
C:\PROGRA~1\QGIS3\apps\Python39\lib\site-packages\win32
C:\PROGRA~1\QGIS3\apps\Python39\lib\site-packages\win32\lib
C:\PROGRA~1\QGIS3\apps\Python39\lib\site-packages\Pythonwin
C:/Users/KAU/AppData/Roaming/QGIS/QGIS3\profiles\tww_test/python
T:/12_GIS/01_QGIS/QGEP/qgep-test/tww_project_2020/test kau
C:\Users/KAU/AppData/Roaming/QGIS/QGIS3\profiles\tww_test/python/plugins\teksi_wastewater\interlis\gui\..\..

**Comment by sjib** [comment] 2024-01-18 16:54
I had this also – could be because the zip is created on a Mac and contains beside a teksi_wastwater folder also a _MACOSX Folder

**Comment by sjib** [comment] 2024-01-18 20:25
![teksi_wastewater zip_with_maxosx_subfolders](https://github.com/teksi/wastewater/assets/1265865/223b9509-9481-4bbf-b080-21ac93db0d61)

**Comment by domi4484** [comment] 2024-01-19 10:12
@urskaufmann I uploaded the newest plugin on the [discussion](https://github.com/teksi/wastewater/discussions/72) main post.
Can you try if you can install the plugin and the export of SIA405 and DSS work?

**Comment by urskaufmann** [comment] 2024-01-19 11:05
Installation of new plugin: OK, no errors
Export DSS of a selection with no missing attributes: works, no errors. If I click an show logs, I get a python-error:
2024-01-19T12:02:44     WARNING    Traceback (most recent call last):
              File "C:\Users/KAU/AppData/Roaming/QGIS/QGIS3\profiles\tww_test/python/plugins\teksi_wastewater\interlis\gui\interlis_importer_exporter_gui.py", line 155, in 
              button.pressed.connect(lambda p=log_path: webbrowser.open(p))
              File "C:\PROGRA~1\QGIS3\apps\Python39\lib\webbrowser.py", line 86, in open
              if browser.open(url, new, autoraise):
              File "C:\PROGRA~1\QGIS3\apps\Python39\lib\webbrowser.py", line 603, in open
              os.startfile(url)
             TypeError: startfile: filepath should be string, bytes or os.PathLike, not NoneType

In the log-file are some warnings:
WARNING  [repeted 9 times]
WARNING  Mapping of wastewater_structure->abwasserbauwerk is not fully implemented.
WARNING  [repeted 18 times]
WARNING  TWW field special_structure.upper_elevation has no equivalent in the interlis model. It will be ignored.
WARNING  Mapping of wastewater_structure->abwasserbauwerk is not fully implemented.
WARNING  TWW field special_structure.upper_elevation has no equivalent in the interlis model. It will be ignored.
WARNING  Mapping of wastewater_structure->abwasserbauwerk is not fully implemented.
WARNING  TWW field wastewater_node.fk_hydr_geometry has no equivalent in the interlis model. It will be ignored.
WARNING  [repeted 10 times]
WARNING  TWW field reach.elevation_determination has no equivalent in the interlis model. It will be ignored.

**Comment by urskaufmann** [comment] 2024-01-19 11:07
I export then with the same selection, DSS with labels. I get error and no export-file:

Ein Fehler trat bei der Ausführung von Python-Code auf: 

AttributeError: 'InterlisExporterToIntermediateSchema' object has no attribute '_export_label_positions' 
Traceback (most recent call last):
  File "C:\Users/KAU/AppData/Roaming/QGIS/QGIS3\profiles\tww_test/python/plugins\teksi_wastewater\teksi_wastewater_plugin.py", line 474, in actionExportClicked
    self.interlisImporterExporter.action_export()
  File "C:\Users/KAU/AppData/Roaming/QGIS/QGIS3\profiles\tww_test/python/plugins\teksi_wastewater\interlis\gui\interlis_importer_exporter_gui.py", line 142, in action_export
    raise exception
  File "C:\Users/KAU/AppData/Roaming/QGIS/QGIS3\profiles\tww_test/python/plugins\teksi_wastewater\interlis\gui\interlis_importer_exporter_gui.py", line 113, in action_export
    self.interlis_importer_exporter.interlis_export(
  File "C:\Users/KAU/AppData/Roaming/QGIS/QGIS3\profiles\tww_test/python/plugins\teksi_wastewater\interlis\interlis_importer_exporter.py", line 157, in interlis_export
    self._export_to_intermediate_schema(
  File "C:\Users/KAU/AppData/Roaming/QGIS/QGIS3\profiles\tww_test/python/plugins\teksi_wastewater\interlis\interlis_importer_exporter.py", line 289, in _export_to_intermediate_schema
    twwInterlisExporter.tww_export()
  File "C:\Users/KAU/AppData/Roaming/QGIS/QGIS3\profiles\tww_test/python/plugins\teksi_wastewater\interlis\interlis_model_mapping\interlis_exporter_to_intermediate_schema.py", line 68, in tww_export
    raise exception
  File "C:\Users/KAU/AppData/Roaming/QGIS/QGIS3\profiles\tww_test/python/plugins\teksi_wastewater\interlis\interlis_model_mapping\interlis_exporter_to_intermediate_schema.py", line 63, in tww_export
    self._export()
  File "C:\Users/KAU/AppData/Roaming/QGIS/QGIS3\profiles\tww_test/python/plugins\teksi_wastewater\interlis\interlis_model_mapping\interlis_exporter_to_intermediate_schema.py", line 92, in _export
    self._export_label_positions()
AttributeError: 'InterlisExporterToIntermediateSchema' object has no attribute '_export_label_positions'

**Comment by urskaufmann** [comment] 2024-01-19 11:11
I export then DSS without selection, without labels (there are missing attributs). I get a better message:
![image](https://github.com/teksi/wastewater/assets/1257403/93452dc4-8ee3-4280-a027-e7d662c50a67)

Show log does not work as described above.

**Comment by 3nids** [comment] 2024-01-23 08:57
should be fixed in last plugin demo, please re-open if needed

**Closed by 3nids** 2024-01-23 08:57 UTC
Labels: bug, plugin, interlis
