### ISSUE TITLE
Interlis Import DSS 2020.1: Unable to import measuring_point objects with damming_device='keiner' 

### ISSUE THREAD

**Issue by taetscher** [teksi/wastewater#303] opened 2024-07-11 11:49 UTC
> Issue was created on behalf of Einwohnergemeinde Zermatt, Abteilung Tiefbau [Kay Korrodi](https://github.com/Kay-Korrodi)

**Describe the bug**
When importing a VSA-DSS 2020.1 XTF containing `measuring_point` objects with `damming_device = 'keiner'`, the import fails, even though the XTF used is valid according to ilivalidator (see [240711093014.tww2ili-import.log](https://github.com/user-attachments/files/16176255/240711093014.tww2ili-import.log)) .

The XTF is being imported just fine into the staging schema (`pg2ili_abwasser`) it seems.

We are currently working under the assumption, that the FK for measuring_point.damming_device is not (correctly) resolved during import into TEKSI WW. In this case for the enum-value `keiner` - which is a valid enum-value in VSA-DSS 2020.1 - the expected FK should be `5721` (see tww_vl -> `measuring_point_damming_device.code`). Due to a lack of understanding of the exact processes at work during mapping of data from pg2ili_abwasser into teksi-schemas we can't confirm this with certainty, though. 

**To Reproduce**
Exact steps to reproduce the behavior:
1. Download [TEKSI-Dev-Plugin](https://github.com/teksi/wastewater/actions/runs/9874446348/artifacts/1686456877) and [dump of PG-DB](https://github.com/teksi/wastewater/actions/runs/9874446345/artifacts/1686457566)
2. Restore Dump obtained from above link
3. Install TEKSI-WW QGIS-Plugin from downloaded .zip file
4. Import organisations (XTF) using import-button
5. Import XTF VSA-DSS 2020.1 (containing `measuring_point` objects with `damming_device = 'keiner'`), using import-button

**Expected behavior**
Since ilivalidator accepts the data, the expected behaviour is a complete import of the XTF into TEKSI-WW

**Screenshots / data**

The following psycopg2 error is thrown:

```SQL
Details: (psycopg2.errors.InvalidTextRepresentation) FEHLER:  ungültige Eingabesyntax für Typ integer: »keiner«
LINE 1: ...wastewater_structure) VALUES ('ch219v9mMP000018', 'keiner', ...
```

<details>
  <summary>
    Complete error message
  </summary>

<p>

```SQL

Details: (psycopg2.errors.InvalidTextRepresentation) FEHLER:  ungültige Eingabesyntax für Typ integer: »keiner«
LINE 1: ...wastewater_structure) VALUES ('ch219v9mMP000018', 'keiner', ...
                                                             ^
[SQL: INSERT INTO tww_od.measuring_point (obj_id, damming_device, identifier, kind, purpose, remark, situation_geometry, last_modification, fk_dataowner, fk_provider, fk_reference_station, fk_operator, fk_waste_water_treatment_plant, fk_wastewater_structur ... 5684 characters truncated ... _16)s, %(fk_operator__16)s, %(fk_waste_water_treatment_plant__16)s, %(fk_wastewater_structure__16)s)]
[parameters: {'damming_device__0': 'keiner', 'purpose__0': 'technischer_Zweck', 'fk_wastewater_structure__0': None, 'fk_waste_water_treatment_plant__0': None, 'obj_id__0': 'ch219v9mMP000018', 'kind__0': 'Wettermessstation', 'identifier__0': 'Meteoschweiz ZER', 'situation_geometry__0': '0101000020080800005a643bcf940544413bdf4f4d65bf3041', 'fk_reference_station__0': None, 'last_modification__0': datetime.date(2023, 10, 16), 'fk_operator__0': None, 'fk_provider__0': 'ch20p3q400001628', 'fk_dataowner__0': 'ch20p3q400001628', 'remark__0': 'WIGOS-ID: 0-20000-0-06748', 'damming_device__1': 'keiner', 'purpose__1': 'technischer_Zweck', 'fk_wastewater_structure__1': None, 'fk_waste_water_treatment_plant__1': None, 'obj_id__1': 'ch219v9mMP000002', 'kind__1': 'Wettermessstation', 'identifier__1': 'MS Schulhaus Hoof', 'situation_geometry__1': '010100002008080000e17a147e61044441df4f8d1706bb3041', 'fk_reference_station__1': None, 'last_modification__1': datetime.date(2023, 9, 11), 'fk_operator__1': 'ch20p3q400001628', 'fk_provider__1': 'ch20p3q400001628', 'fk_dataowner__1': 'ch20p3q400001628', 'remark__1': None, 'damming_device__2': 'unbekannt', 'purpose__2': 'technischer_Zweck', 'fk_wastewater_structure__2': None, 'fk_waste_water_treatment_plant__2': None, 'obj_id__2': 'ch219v9mMP000012', 'kind__2': 'Abflussmessung', 'identifier__2': 'Sunneggastr Vispastr', 'situation_geometry__2': '0101000020080800006f1283508f0544416de7fbc947bd3041', 'fk_reference_station__2': None, 'last_modification__2': datetime.date(2023, 10, 4), 'fk_operator__2': 'ch20p3q400001628', 'fk_provider__2': 'ch20p3q400001628', 'fk_dataowner__2': 'ch20p3q400001628', 'remark__2': '4-400-05-M; Abflussmessungen temporaer installiert', 'damming_device__3': 'unbekannt', 'purpose__3': 'technischer_Zweck', 'fk_wastewater_structure__3': None, 'fk_waste_water_treatment_plant__3': None, 'obj_id__3': 'ch219v9mMP000013', 'kind__3': 'Abflussmessung', 'identifier__3': 'Friedhof NIVUS', 'situation_geometry__3': '01010000200808000089416065f80444411283c04a1dbb3041' ... 138 parameters truncated ... 'identifier__13': 'Schreinerei Brigger', 'situation_geometry__13': '010100002008080000643bdfefc90544418fc2f528f3be3041', 'fk_reference_station__13': None, 'last_modification__13': datetime.date(2023, 10, 4), 'fk_operator__13': 'ch20p3q400001628', 'fk_provider__13': 'ch20p3q400001628', 'fk_dataowner__13': 'ch20p3q400001628', 'remark__13': '2-100-06-M; falsche bezeichnung Messdaten, Abflussmessungen temporaer', 'damming_device__14': 'unbekannt', 'purpose__14': 'technischer_Zweck', 'fk_wastewater_structure__14': None, 'fk_waste_water_treatment_plant__14': None, 'obj_id__14': 'ch219v9mMP000011', 'kind__14': 'Abflussmessung', 'identifier__14': 'Uferweg', 'situation_geometry__14': '010100002008080000f4fdd4981d0544413f355e1a9fbb3041', 'fk_reference_station__14': None, 'last_modification__14': datetime.date(2023, 10, 4), 'fk_operator__14': 'ch20p3q400001628', 'fk_provider__14': 'ch20p3q400001628', 'fk_dataowner__14': 'ch20p3q400001628', 'remark__14': '5-300-04-M; falsche Verknuepfung, Abflussmessungen temporaer installiert', 'damming_device__15': 'unbekannt', 'purpose__15': 'technischer_Zweck', 'fk_wastewater_structure__15': None, 'fk_waste_water_treatment_plant__15': None, 'obj_id__15': 'ch219v9mMP000014', 'kind__15': 'Abflussmessung', 'identifier__15': 'Zen Steckenstrasse', 'situation_geometry__15': '0101000020080800006de7fb292004444104560e8da6b93041', 'fk_reference_station__15': None, 'last_modification__15': datetime.date(2023, 10, 4), 'fk_operator__15': 'ch20p3q400001628', 'fk_provider__15': 'ch20p3q400001628', 'fk_dataowner__15': 'ch20p3q400001628', 'remark__15': '3-800-47-M; Abflussmessungen temporaer installiert', 'damming_device__16': 'unbekannt', 'purpose__16': 'technischer_Zweck', 'fk_wastewater_structure__16': None, 'fk_waste_water_treatment_plant__16': None, 'obj_id__16': 'ch219v9mMP000015', 'kind__16': 'Abflussmessung', 'identifier__16': 'ZenStecken Armietf', 'situation_geometry__16': '0101000020080800001283c0aae1034441273108ac6ab83041', 'fk_reference_station__16': None, 'last_modification__16': datetime.date(2023, 10, 4), 'fk_operator__16': 'ch20p3q400001628', 'fk_provider__16': 'ch20p3q400001628', 'fk_dataowner__16': 'ch20p3q400001628', 'remark__16': '6-400-21-M; Abflussmessungen temporaer installiert'}]
(Background on this error at: https://sqlalche.me/e/20/9h9h)

```

</details>

This is the object in question:

```XML
<DSS_2020_1_LV95.Siedlungsentwaesserung.Messstelle TID="ch219v9mMP000018">
    <Letzte_Aenderung>20231016</Letzte_Aenderung>
    <DatenherrRef REF="ch20p3q400001628"></DatenherrRef>
    <DatenlieferantRef REF="ch20p3q400001628"></DatenlieferantRef>
    <Art>Wettermessstation</Art>
    <Bemerkung>WIGOS-ID: 0-20000-0-06748</Bemerkung>
    <Bezeichnung>Meteoschweiz ZER</Bezeichnung>
    <Lage>
        <COORD>
            <C1>2624297.619</C1>
            <C2>1097573.302</C2>
        </COORD>
    </Lage>
    <Staukoerper>keiner</Staukoerper>
    <Zweck>technischer_Zweck</Zweck>
</DSS_2020_1_LV95.Siedlungsentwaesserung.Messstelle>
```

It seems as though the FK-relation between damming_device and the value-list inside tww_vl is defined:
```SQL
CREATE TABLE IF NOT EXISTS tww_od.measuring_point
(
    obj_id character varying(16) COLLATE pg_catalog."default" NOT NULL DEFAULT tww_sys.generate_oid('tww_od'::text, 'measuring_point'::text),
    damming_device integer,
    identifier text COLLATE pg_catalog."default",
    kind text COLLATE pg_catalog."default",
    purpose integer,
    remark text COLLATE pg_catalog."default",
    situation_geometry geometry(Point,2056),
    last_modification timestamp without time zone DEFAULT now(),
    fk_dataowner character varying(16) COLLATE pg_catalog."default" DEFAULT tww_sys.get_default_values('fk_dataowner'::text),
    fk_provider character varying(16) COLLATE pg_catalog."default" DEFAULT tww_sys.get_default_values('fk_provider'::text),
    fk_reference_station character varying(16) COLLATE pg_catalog."default",
    fk_operator character varying(16) COLLATE pg_catalog."default",
    fk_waste_water_treatment_plant character varying(16) COLLATE pg_catalog."default",
    fk_wastewater_structure character varying(16) COLLATE pg_catalog."default",
    CONSTRAINT pkey_tww_od_measuring_point_obj_id PRIMARY KEY (obj_id),
    CONSTRAINT fkey_vl_measuring_point_damming_device FOREIGN KEY (damming_device)
        REFERENCES tww_vl.measuring_point_damming_device (code) MATCH SIMPLE
        ON UPDATE RESTRICT
        ON DELETE RESTRICT,
[...]
```

The complete XTF used can be provided with explicit approval from Einwohnergemeinde Zermatt, Abteilung Tiefbau and is therefore not attached to this issue.

**Desktop (please complete the following information):**
 - TWW version ( idk, 0.0.0?, see links above for artifacts used to test, there were manual downloads from github involved ... :) )
 - QGIS Version 3.38 Grenoble
 - OS Windows 11

**Additional context**
None

**Comment by sjib** [comment] 2024-07-11 14:10
The value list looks ok to me in the data model:
![20240711_measuring_point_damming_device](https://github.com/teksi/wastewater/assets/1265865/98f6f052-2eee-4ca9-833b-1b449784951e)

@taetscher Can you check with this data set if you get the same error on import? 
Just one measuring_point with damming_device = none
[test-dataset-mesuring_point.xtf.zip](https://github.com/user-attachments/files/16178677/test-dataset-mesuring_point.xtf.zip)

**Comment by sjib** [comment] 2024-07-11 14:17
@taetscher If it is not working, can you take out the value 'none' in damming_device and check if it works without a value?

**Comment by taetscher** [comment] 2024-07-11 14:35
@sjib 

Thank you for the isolated test case.
After testing I can report the following:

- using test-dataset-measuring_point.xtf as provided
    - This does indeed throw the same error:
    - ![image](https://github.com/teksi/wastewater/assets/24844442/a8169114-fcd0-4e46-a683-b0c9c1de775b)

- removing the attribute `damming_device` in xtf completely
    - throws the same error for (presumably) the same reasons but in attribute `purpose`:
    - ![image](https://github.com/teksi/wastewater/assets/24844442/04d17040-528c-47f2-a907-092b347be490)

- removing both attributes `damming_device` and `purpose` in xtf
    - import is now possible
    - ![image](https://github.com/teksi/wastewater/assets/24844442/de0edfce-2cee-4c82-a6ec-45d6cef72f54)


<details>
  <summary>
    (Working) Measuring_Point Object after deletion of both attributes
  </summary>

```XML
<?xml version="1.0" encoding="UTF-8"?>
<TRANSFER xmlns="http://www.interlis.ch/INTERLIS2.3">
	<HEADERSECTION VERSION="2.3" SENDER="UNKNOWN">
		<MODELS>
			<MODEL NAME="Units" VERSION="2012-02-20" URI="http://www.interlis.ch/models" />
			<MODEL NAME="Base" VERSION="18.4.2014" URI="http://www.sia.ch/405" />
			<MODEL NAME="SIA405_Base_Abwasser_1_LV95" VERSION="18.10.2023" URI="http://www.vsa.ch/models" />
			<MODEL NAME="DSS_2020_1_LV95" URI="http://www.vsa.ch/models" VERSION="18.10.2023"/>
		</MODELS>
		<COMMENT>11.7.2024 dataset manually generated by Stefan Burckhardt - nur Messstelle</COMMENT>


	</HEADERSECTION>
	<DATASECTION>
		<DSS_2020_1_LV95.Siedlungsentwaesserung BID="xBASKET1">
			<DSS_2020_1_LV95.Siedlungsentwaesserung.Messstelle TID="ch080qwzMS001300">






				<Letzte_Aenderung>20191014</Letzte_Aenderung>
				<DatenherrRef REF="ch20p3q400001628"/>
				<DatenlieferantRef REF="ch20p3q400001628"/>

				<Art>Regenmessung</Art>
				<Bezeichnung>Aletsch13</Bezeichnung>
				<Lage>
					<COORD>
						<C1>2647500.000</C1>
						<C2>1148500.000</C2>
					</COORD>
				</Lage>
				

				<BetreiberRef REF="ch20p3q400001628"/>
			</DSS_2020_1_LV95.Siedlungsentwaesserung.Messstelle>
		</DSS_2020_1_LV95.Siedlungsentwaesserung>
	</DATASECTION>
</TRANSFER>

```

</details>

**Comment by sjib** [comment] 2024-07-11 20:38
@taetscher Thanks for the detailed analysis. The problem is indeed in the import / export configuration where these attributes were not treated as attributes with value lists.

Should be fixed with https://github.com/teksi/wastewater/pull/304 - you can check the changes.
I found some more bugs concerning VSA-KEK that I am still working on.

**Comment by Kay-Korrodi** [comment] 2024-07-12 06:06
Danke für Euren Einsatz. Bin gespannt ob wir bald mal unsere Arbeiten mit 2020.1 loslegen können :) @taetscher

**Comment by ponceta** [comment] 2024-07-12 14:07
Fix is merged, please have a try with this or the latest version of the plugin (not released yet)
[teksi_wastewater.0.0.0.zip](https://github.com/user-attachments/files/16195113/teksi_wastewater.0.0.0.zip)

**Comment by taetscher** [comment] 2024-07-15 11:13
@ponceta Thank you for letting us know about the merge. For some reason when I try to download the file in your comment, i get an empty .zip. I assume using the artifact from [here](https://github.com/teksi/wastewater/actions/runs/9908083683) should work as well, right?

**Comment by sjib** [comment] 2024-07-15 11:52
@taetscher I can confirm - the zip from Arnaud is emtpy. The `teksi_wastewater_plugin_dev` in the linked artefact should indeed also work - @ponceta Can you confirm?

**Comment by ponceta** [comment] 2024-07-16 08:20
Please reopen if not solved.

**Closed by ponceta** 2024-07-16 08:20 UTC
Labels: bug, INTERLIS

**Comment by taetscher** [comment] 2024-07-16 11:00
@Kay-Korrodi @ponceta @sjib 
I can confirm that the import worked.

Thank you for your fast response and fixing of this issue. 🚀

**Comment by Kay-Korrodi** [comment] 2024-07-16 11:09
Many Thanks to all of you for your hard work on it! We try to work with it now 👍

**Comment by sjib** [comment] 2024-07-16 11:14
@Kay-Korrodi @taetscher Thanks for your feedback. Hope it works as expected. 

Please do not hesitate to open new issues if needed. There are too many possible traps so that not everyone has to step into (-:
